### ISSUE TITLE
Error messages when trying to run a site with the ruby TLC: "Not implemented"

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp#23]
When trying to test the ruby TLC, I start with:
`$ bundle exec rsmp site`

But after I start rspec, I soon get a lot of these kinds of errors:

`Status S0012/status not implemented by RSMP::Component`

What am I doing wrong?

**Comment by emiltin** [comment]
it's because you're running a generic RSMP site. You probably want to run a TLC, and use a config file:

```console
bundle exec rsmp site --type tlc --config config/tlc.yaml --supervisors :13111
```

The supervisoi ip/port can also be specified in the config file. In config/tlc.yaml, the standard port 12111 is specified, but the velidator uses 13111 to avoid interferring with stuff running on the default port. That's why the command above specifies the port. You can change it the config file instead if you like.

**Comment by emiltin** [comment]
You can run the help command to see what options you can pass:

```shell
% bundle exec rsmp help site
Usage:
  rsmp site

Options:
  -c, [--config=Path to .yaml config file]                          
  -i, [--id=RSMP site id]                                           
  -s, [--supervisors=ip:port,... list of supervisor to connect to]  
  -l, [--log=Path to log file]                                      
  -j, [--json=Show JSON messages in log], [--no-json]               
  -t, [--type=Type of site: [tlc]]                                  

Run RSMP site
```

**Comment by otterdahl** [comment]
Thanks. Now it works great.

**Comment by emiltin** [comment]
For reference, see http://rsmp-nordic.org/rsmp_validator/testing/#running-tests-again-a-local-ruby-tlc-site
